const ExploreMockData = [
  {
    id: 1,
    username: "Maro Org",
    time: "1h",
    profileImg: "http://pawtopia.scarlet2.io/images/image1.png",
    postImgs: [
      "http://pawtopia.scarlet2.io/images/explore1.jpg",
      "http://pawtopia.scarlet2.io/images/image2.png",
      "http://pawtopia.scarlet2.io/images/image3.png",
    ],
    mutualFrndImg1: "https://source.unsplash.com/random/?boy",
    mutualFrndImg2: "https://source.unsplash.com/random/?girl",
    likeCount: "1,200",
    caption:
      "Bella is a 2-year-old meow with a heart full of love. She’s energetic, playful, and great with kids. Bella loves long walks, belly rubs, and chasing after her favorite toys.",
    commentCount: "100",
    isVerified: true,
    tags: ["Cebu City", "Puspin", "Trauma due to car crash"],
  },
  {
    id: 2,
    username: "PetAdopt",
    time: "2h",
    profileImg: "http://pawtopia.scarlet2.io/images/image4.png",
    postImgs: [
      "http://pawtopia.scarlet2.io/images/explore2.jpg",
      "http://pawtopia.scarlet2.io/images/image5.png",
    ],
    mutualFrndImg1: "https://source.unsplash.com/random/?woman",
    mutualFrndImg2: "https://source.unsplash.com/random/?man",
    likeCount: "980",
    caption:
      "Meet Max, the Beagle with a big heart! He loves outdoor adventures.",
    commentCount: "87",
    isVerified: false,
    tags: ["Cebu City", "Beagle", "Dog Lover", "Outdoor Adventures"],
  },
  {
    id: 3,
    username: "HappyTails",
    time: "3h",
    profileImg: "http://pawtopia.scarlet2.io/images/image6.png",
    postImgs: [
      "http://pawtopia.scarlet2.io/images/explore3.jpg",
      "http://pawtopia.scarlet2.io/images/image7.png",
      "http://pawtopia.scarlet2.io/images/image8.png",
    ],
    mutualFrndImg1: "https://source.unsplash.com/random/?girl",
    mutualFrndImg2: "https://source.unsplash.com/random/?dog",
    likeCount: "2,300",
    caption: "Luna is a Siberian Husky with striking blue eyes.",
    commentCount: "120",
    isVerified: true,
    tags: ["Cebu City", "Husky", "Snow Lover", "AdoptDontShop"],
  },
  {
    id: 4,
    username: "AnimalShelter",
    time: "5h",
    profileImg: "http://pawtopia.scarlet2.io/images/image9.png",
    postImgs: [
      "http://pawtopia.scarlet2.io/images/explore4.jpg",
      "http://pawtopia.scarlet2.io/images/image10.png",
    ],
    mutualFrndImg1: "https://source.unsplash.com/random/?dog",
    mutualFrndImg2: "https://source.unsplash.com/random/?cat",
    likeCount: "1,800",
    caption: "Rocky is a Bulldog with a lovable personality.",
    commentCount: "95",
    isVerified: false,
    tags: ["Cebu City", "Bulldog", "Loyal Friend", "Shelter Dog"],
  },
  {
    id: 5,
    username: "FurryFriends",
    time: "6h",
    profileImg: "http://pawtopia.scarlet2.io/images/image11.png",
    postImgs: [
      "http://pawtopia.scarlet2.io/images/explore5.jpg",
      "http://pawtopia.scarlet2.io/images/image12.png",
    ],
    mutualFrndImg1: "https://source.unsplash.com/random/?puppy",
    mutualFrndImg2: "https://source.unsplash.com/random/?kitten",
    likeCount: "1,500",
    caption: "Daisy is a Poodle with a cheerful disposition.",
    commentCount: "80",
    isVerified: true,
    tags: ["Cebu City", "Poodle", "Small Dog", "AdoptDontShop"],
  },
  {
    id: 6,
    username: "DoggieDreams",
    time: "4h",
    profileImg: "http://pawtopia.scarlet2.io/images/image13.png",
    postImgs: ["http://pawtopia.scarlet2.io/images/explore6.jpg"],
    mutualFrndImg1: "https://source.unsplash.com/random/?animal",
    mutualFrndImg2: "https://source.unsplash.com/random/?child",
    likeCount: "2,800",
    caption: "Charlie is a loving Labrador looking for a home.",
    commentCount: "140",
    isVerified: false,
    tags: ["Cebu City", "Labrador", "Family Dog", "Adoption"],
  },
  {
    id: 7,
    username: "FurHaven",
    time: "7h",
    profileImg: "http://pawtopia.scarlet2.io/images/image14.png",
    postImgs: ["http://pawtopia.scarlet2.io/images/explore7.jpg"],
    mutualFrndImg1: "https://source.unsplash.com/random/?boy",
    mutualFrndImg2: "https://source.unsplash.com/random/?girl",
    likeCount: "3,100",
    caption: "Bailey is a sweet Dachshund who loves cuddles.",
    commentCount: "200",
    isVerified: true,
    tags: ["Cebu City", "Dachshund", "Cuddle Buddy", "Rescue Dog"],
  },
  {
    id: 8,
    username: "AdoptAPaw",
    time: "8h",
    profileImg: "http://pawtopia.scarlet2.io/images/image15.png",
    postImgs: ["http://pawtopia.scarlet2.io/images/explore8.jpg"],
    mutualFrndImg1: "https://source.unsplash.com/random/?dog",
    mutualFrndImg2: "https://source.unsplash.com/random/?woman",
    likeCount: "1,900",
    caption: "Meet Cooper, a Golden Retriever who loves to play fetch.",
    commentCount: "110",
    isVerified: true,
    tags: ["Cebu City", "Golden Retriever", "Playful", "Rescue Dog"],
  },
  {
    id: 9,
    username: "PawPatrol",
    time: "10h",
    profileImg: "http://pawtopia.scarlet2.io/images/image16.png",
    postImgs: ["http://pawtopia.scarlet2.io/images/explore9.jpg"],
    mutualFrndImg1: "https://source.unsplash.com/random/?puppy",
    mutualFrndImg2: "https://source.unsplash.com/random/?kitten",
    likeCount: "1,700",
    caption: "Rex is a German Shepherd who loves to protect and serve.",
    commentCount: "130",
    isVerified: false,
    tags: ["Cebu City", "German Shepherd", "Protector", "Adoption"],
  },
];

export default ExploreMockData;
